version: "3"

services:
  redis:
    image: redis:alpine
    container_name: redis

  container1:
    build: ./container1
    depends_on:
      - redis
    command: ["python", "/test.py"]

  container2:
    build: ./container2
    depends_on:
      - redis
    command: ["python", "/test.py"]

  container3:
    build: ./container3
    depends_on:
      - redis
    command: ["python", "/test.py"]

  container4:
    build: ./container4
    depends_on:
      - redis
    command: ["python", "/test.py"]
